// const http = require("http");

// const htmlContent = `
//       <!DOCTYPE html>
//       <html>
//           <head>
//               <title>Food</title>
//           </head>
//           <body>

//               <script>
//               fetch("http://localhost:3344")
//               .then(res=>res.json())
//               .then(data=>console.log(data=>{
//                   let listEl = document.getElementById()
//                   data.forEach(li=>{
//                       document.createElement("li");

//                   })
//               })
//               .catch(err=>console.log(err))
//               </script>
//           </body>
//       </html>
//   `;

// //the request is generated by node, the data is given by whatever is trying to access server
// // response sends info back

// const server = http.createServer((req, res) => {
//   res.statusCode = 200;
//   console.log(res);
//   res.end(htmlContent);
// });

// server.listen(3344, () => {
//   console.log("The server is up and running, listening on port 3344");
// });
